/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParentsRouteRouteImport } from './routes/parents/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StuffIndexRouteImport } from './routes/stuff/index'
import { Route as ParentsIndexRouteImport } from './routes/parents/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ParentsNewsRouteImport } from './routes/parents/news'
import { Route as ParentsMessageRouteImport } from './routes/parents/message'
import { Route as ParentsEmergenciesRouteImport } from './routes/parents/emergencies'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as StuffPostsIndexRouteImport } from './routes/stuff/posts/index'
import { Route as StuffMessagesIndexRouteImport } from './routes/stuff/messages/index'
import { Route as StuffGroupsIndexRouteImport } from './routes/stuff/groups/index'
import { Route as StuffPostsPostIdRouteImport } from './routes/stuff/posts/$postId'
import { Route as StuffMessagesThreadIdRouteImport } from './routes/stuff/messages/$threadId'
import { Route as StuffGroupsGroupIdRouteImport } from './routes/stuff/groups/$groupId'

const ParentsRouteRoute = ParentsRouteRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StuffIndexRoute = StuffIndexRouteImport.update({
  id: '/stuff/',
  path: '/stuff/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsIndexRoute = ParentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentsRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ParentsNewsRoute = ParentsNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => ParentsRouteRoute,
} as any)
const ParentsMessageRoute = ParentsMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => ParentsRouteRoute,
} as any)
const ParentsEmergenciesRoute = ParentsEmergenciesRouteImport.update({
  id: '/emergencies',
  path: '/emergencies',
  getParentRoute: () => ParentsRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const StuffPostsIndexRoute = StuffPostsIndexRouteImport.update({
  id: '/stuff/posts/',
  path: '/stuff/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const StuffMessagesIndexRoute = StuffMessagesIndexRouteImport.update({
  id: '/stuff/messages/',
  path: '/stuff/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const StuffGroupsIndexRoute = StuffGroupsIndexRouteImport.update({
  id: '/stuff/groups/',
  path: '/stuff/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const StuffPostsPostIdRoute = StuffPostsPostIdRouteImport.update({
  id: '/stuff/posts/$postId',
  path: '/stuff/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const StuffMessagesThreadIdRoute = StuffMessagesThreadIdRouteImport.update({
  id: '/stuff/messages/$threadId',
  path: '/stuff/messages/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const StuffGroupsGroupIdRoute = StuffGroupsGroupIdRouteImport.update({
  id: '/stuff/groups/$groupId',
  path: '/stuff/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/parents': typeof ParentsRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/parents/emergencies': typeof ParentsEmergenciesRoute
  '/parents/message': typeof ParentsMessageRoute
  '/parents/news': typeof ParentsNewsRoute
  '/admin/': typeof AdminIndexRoute
  '/parents/': typeof ParentsIndexRoute
  '/stuff/': typeof StuffIndexRoute
  '/stuff/groups/$groupId': typeof StuffGroupsGroupIdRoute
  '/stuff/messages/$threadId': typeof StuffMessagesThreadIdRoute
  '/stuff/posts/$postId': typeof StuffPostsPostIdRoute
  '/stuff/groups/': typeof StuffGroupsIndexRoute
  '/stuff/messages/': typeof StuffMessagesIndexRoute
  '/stuff/posts/': typeof StuffPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/parents/emergencies': typeof ParentsEmergenciesRoute
  '/parents/message': typeof ParentsMessageRoute
  '/parents/news': typeof ParentsNewsRoute
  '/admin': typeof AdminIndexRoute
  '/parents': typeof ParentsIndexRoute
  '/stuff': typeof StuffIndexRoute
  '/stuff/groups/$groupId': typeof StuffGroupsGroupIdRoute
  '/stuff/messages/$threadId': typeof StuffMessagesThreadIdRoute
  '/stuff/posts/$postId': typeof StuffPostsPostIdRoute
  '/stuff/groups': typeof StuffGroupsIndexRoute
  '/stuff/messages': typeof StuffMessagesIndexRoute
  '/stuff/posts': typeof StuffPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/parents': typeof ParentsRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/parents/emergencies': typeof ParentsEmergenciesRoute
  '/parents/message': typeof ParentsMessageRoute
  '/parents/news': typeof ParentsNewsRoute
  '/admin/': typeof AdminIndexRoute
  '/parents/': typeof ParentsIndexRoute
  '/stuff/': typeof StuffIndexRoute
  '/stuff/groups/$groupId': typeof StuffGroupsGroupIdRoute
  '/stuff/messages/$threadId': typeof StuffMessagesThreadIdRoute
  '/stuff/posts/$postId': typeof StuffPostsPostIdRoute
  '/stuff/groups/': typeof StuffGroupsIndexRoute
  '/stuff/messages/': typeof StuffMessagesIndexRoute
  '/stuff/posts/': typeof StuffPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/parents'
    | '/auth/login'
    | '/auth/register'
    | '/parents/emergencies'
    | '/parents/message'
    | '/parents/news'
    | '/admin/'
    | '/parents/'
    | '/stuff/'
    | '/stuff/groups/$groupId'
    | '/stuff/messages/$threadId'
    | '/stuff/posts/$postId'
    | '/stuff/groups/'
    | '/stuff/messages/'
    | '/stuff/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/parents/emergencies'
    | '/parents/message'
    | '/parents/news'
    | '/admin'
    | '/parents'
    | '/stuff'
    | '/stuff/groups/$groupId'
    | '/stuff/messages/$threadId'
    | '/stuff/posts/$postId'
    | '/stuff/groups'
    | '/stuff/messages'
    | '/stuff/posts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/parents'
    | '/auth/login'
    | '/auth/register'
    | '/parents/emergencies'
    | '/parents/message'
    | '/parents/news'
    | '/admin/'
    | '/parents/'
    | '/stuff/'
    | '/stuff/groups/$groupId'
    | '/stuff/messages/$threadId'
    | '/stuff/posts/$postId'
    | '/stuff/groups/'
    | '/stuff/messages/'
    | '/stuff/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ParentsRouteRoute: typeof ParentsRouteRouteWithChildren
  StuffIndexRoute: typeof StuffIndexRoute
  StuffGroupsGroupIdRoute: typeof StuffGroupsGroupIdRoute
  StuffMessagesThreadIdRoute: typeof StuffMessagesThreadIdRoute
  StuffPostsPostIdRoute: typeof StuffPostsPostIdRoute
  StuffGroupsIndexRoute: typeof StuffGroupsIndexRoute
  StuffMessagesIndexRoute: typeof StuffMessagesIndexRoute
  StuffPostsIndexRoute: typeof StuffPostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stuff/': {
      id: '/stuff/'
      path: '/stuff'
      fullPath: '/stuff/'
      preLoaderRoute: typeof StuffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/': {
      id: '/parents/'
      path: '/'
      fullPath: '/parents/'
      preLoaderRoute: typeof ParentsIndexRouteImport
      parentRoute: typeof ParentsRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/parents/news': {
      id: '/parents/news'
      path: '/news'
      fullPath: '/parents/news'
      preLoaderRoute: typeof ParentsNewsRouteImport
      parentRoute: typeof ParentsRouteRoute
    }
    '/parents/message': {
      id: '/parents/message'
      path: '/message'
      fullPath: '/parents/message'
      preLoaderRoute: typeof ParentsMessageRouteImport
      parentRoute: typeof ParentsRouteRoute
    }
    '/parents/emergencies': {
      id: '/parents/emergencies'
      path: '/emergencies'
      fullPath: '/parents/emergencies'
      preLoaderRoute: typeof ParentsEmergenciesRouteImport
      parentRoute: typeof ParentsRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/stuff/posts/': {
      id: '/stuff/posts/'
      path: '/stuff/posts'
      fullPath: '/stuff/posts/'
      preLoaderRoute: typeof StuffPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stuff/messages/': {
      id: '/stuff/messages/'
      path: '/stuff/messages'
      fullPath: '/stuff/messages/'
      preLoaderRoute: typeof StuffMessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stuff/groups/': {
      id: '/stuff/groups/'
      path: '/stuff/groups'
      fullPath: '/stuff/groups/'
      preLoaderRoute: typeof StuffGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stuff/posts/$postId': {
      id: '/stuff/posts/$postId'
      path: '/stuff/posts/$postId'
      fullPath: '/stuff/posts/$postId'
      preLoaderRoute: typeof StuffPostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stuff/messages/$threadId': {
      id: '/stuff/messages/$threadId'
      path: '/stuff/messages/$threadId'
      fullPath: '/stuff/messages/$threadId'
      preLoaderRoute: typeof StuffMessagesThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stuff/groups/$groupId': {
      id: '/stuff/groups/$groupId'
      path: '/stuff/groups/$groupId'
      fullPath: '/stuff/groups/$groupId'
      preLoaderRoute: typeof StuffGroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ParentsRouteRouteChildren {
  ParentsEmergenciesRoute: typeof ParentsEmergenciesRoute
  ParentsMessageRoute: typeof ParentsMessageRoute
  ParentsNewsRoute: typeof ParentsNewsRoute
  ParentsIndexRoute: typeof ParentsIndexRoute
}

const ParentsRouteRouteChildren: ParentsRouteRouteChildren = {
  ParentsEmergenciesRoute: ParentsEmergenciesRoute,
  ParentsMessageRoute: ParentsMessageRoute,
  ParentsNewsRoute: ParentsNewsRoute,
  ParentsIndexRoute: ParentsIndexRoute,
}

const ParentsRouteRouteWithChildren = ParentsRouteRoute._addFileChildren(
  ParentsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ParentsRouteRoute: ParentsRouteRouteWithChildren,
  StuffIndexRoute: StuffIndexRoute,
  StuffGroupsGroupIdRoute: StuffGroupsGroupIdRoute,
  StuffMessagesThreadIdRoute: StuffMessagesThreadIdRoute,
  StuffPostsPostIdRoute: StuffPostsPostIdRoute,
  StuffGroupsIndexRoute: StuffGroupsIndexRoute,
  StuffMessagesIndexRoute: StuffMessagesIndexRoute,
  StuffPostsIndexRoute: StuffPostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
