/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ParentsRouteRouteImport } from './routes/parents/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParentsIndexRouteImport } from './routes/parents/index'
import { Route as ParentsNewsRouteImport } from './routes/parents/news'
import { Route as ParentsMessageRouteImport } from './routes/parents/message'
import { Route as ParentsEmergenciesRouteImport } from './routes/parents/emergencies'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRouteRoute = ParentsRouteRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsIndexRoute = ParentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentsRouteRoute,
} as any)
const ParentsNewsRoute = ParentsNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => ParentsRouteRoute,
} as any)
const ParentsMessageRoute = ParentsMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => ParentsRouteRoute,
} as any)
const ParentsEmergenciesRoute = ParentsEmergenciesRouteImport.update({
  id: '/emergencies',
  path: '/emergencies',
  getParentRoute: () => ParentsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parents': typeof ParentsRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/parents/emergencies': typeof ParentsEmergenciesRoute
  '/parents/message': typeof ParentsMessageRoute
  '/parents/news': typeof ParentsNewsRoute
  '/parents/': typeof ParentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/parents/emergencies': typeof ParentsEmergenciesRoute
  '/parents/message': typeof ParentsMessageRoute
  '/parents/news': typeof ParentsNewsRoute
  '/parents': typeof ParentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parents': typeof ParentsRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/parents/emergencies': typeof ParentsEmergenciesRoute
  '/parents/message': typeof ParentsMessageRoute
  '/parents/news': typeof ParentsNewsRoute
  '/parents/': typeof ParentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/parents'
    | '/auth'
    | '/parents/emergencies'
    | '/parents/message'
    | '/parents/news'
    | '/parents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/parents/emergencies'
    | '/parents/message'
    | '/parents/news'
    | '/parents'
  id:
    | '__root__'
    | '/'
    | '/parents'
    | '/auth'
    | '/parents/emergencies'
    | '/parents/message'
    | '/parents/news'
    | '/parents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParentsRouteRoute: typeof ParentsRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/': {
      id: '/parents/'
      path: '/'
      fullPath: '/parents/'
      preLoaderRoute: typeof ParentsIndexRouteImport
      parentRoute: typeof ParentsRouteRoute
    }
    '/parents/news': {
      id: '/parents/news'
      path: '/news'
      fullPath: '/parents/news'
      preLoaderRoute: typeof ParentsNewsRouteImport
      parentRoute: typeof ParentsRouteRoute
    }
    '/parents/message': {
      id: '/parents/message'
      path: '/message'
      fullPath: '/parents/message'
      preLoaderRoute: typeof ParentsMessageRouteImport
      parentRoute: typeof ParentsRouteRoute
    }
    '/parents/emergencies': {
      id: '/parents/emergencies'
      path: '/emergencies'
      fullPath: '/parents/emergencies'
      preLoaderRoute: typeof ParentsEmergenciesRouteImport
      parentRoute: typeof ParentsRouteRoute
    }
  }
}

interface ParentsRouteRouteChildren {
  ParentsEmergenciesRoute: typeof ParentsEmergenciesRoute
  ParentsMessageRoute: typeof ParentsMessageRoute
  ParentsNewsRoute: typeof ParentsNewsRoute
  ParentsIndexRoute: typeof ParentsIndexRoute
}

const ParentsRouteRouteChildren: ParentsRouteRouteChildren = {
  ParentsEmergenciesRoute: ParentsEmergenciesRoute,
  ParentsMessageRoute: ParentsMessageRoute,
  ParentsNewsRoute: ParentsNewsRoute,
  ParentsIndexRoute: ParentsIndexRoute,
}

const ParentsRouteRouteWithChildren = ParentsRouteRoute._addFileChildren(
  ParentsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParentsRouteRoute: ParentsRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
